#!/bin/sh

#
# This script is a part of otfbeta-uptex (a.k.a. japanese-otf-uptex).
#

#OVP2OVF='omfonts -ovp2ovf'
#OVP2OVF='wovp2ovf'
#export OVP2OVF

if test ! -d tfm; then
mkdir tfm
fi


echo "making tfm for burasage ..."
for series in nml exp
do
for face in minr gothr minb gothb mgothr
do
uppltotf -kanji=uptex basepl/ubrsg-h.pl tfm/upbrsg${series}${face}-h.tfm
uppltotf -kanji=uptex basepl/ubrsg-v.pl tfm/upbrsg${series}${face}-v.tfm
done
done
#extra fonts
for series in nml exp
do
for face in gotheb minl
do
uppltotf -kanji=uptex basepl/ubrsg-h.pl tfm/upbrsg${series}${face}-h.tfm
uppltotf -kanji=uptex basepl/ubrsg-v.pl tfm/upbrsg${series}${face}-v.tfm
done
done


echo "making vf for burasage ..."
for face in minr gothr minb gothb mgothr
do
./umkjvf -ucs -sp 1 -sage -cq     upbrsgnml${face}-h uph${face}-h
./umkjvf -ucs -sp 1 -sage -cm -cp upbrsgnml${face}-v uph${face}-v
done
#extra fonts
for face in gotheb minl
do
./umkjvf -ucs -sp 1 -sage -cq     upbrsgnml${face}-h uph${face}-h
./umkjvf -ucs -sp 1 -sage -cm -cp upbrsgnml${face}-v uph${face}-v
done
for face in minr gothr minb gothb mgothr
do
./umkjvf -ucs -sp 1 -sage -cq     -expert upbrsgexp${face}-h uph${face}-h cidj${face}
./umkjvf -ucs -sp 1 -sage -cm -cp -expert upbrsgexp${face}-v uph${face}-v cidj${face}
done
#extra fonts
for face in gotheb minl
do
./umkjvf -ucs -sp 1 -sage -cq     -expert upbrsgexp${face}-h uph${face}-h cidj${face}
./umkjvf -ucs -sp 1 -sage -cm -cp -expert upbrsgexp${face}-v uph${face}-v cidj${face}
done


echo "finishing ..."
if test ! -d vf; then
mkdir vf
fi
mv *.vf vf/
mv *.tfm tfm/
